### ISSUE TITLE
Enumerable#inject has incorrect examples

### ISSUE THREAD

**Issue by bambery** [ruby/rdoc#1006]
The #inject method has multiple incorrect examples given _outside_ of a codeblock. The examples within codeblocks are correct.
https://ruby-doc.org/3.2.2/Enumerable.html#method-i-inject

The incorrect examples outside of the codeblock:

- `(1..4).inject(:+) =>[1, 2, 3, 4]` - correct answer is `10`,
- `(1...4).inject(:+) => [1, 2, 3]` - correct answer is `6`,
- `('a'..'d').inject(:+) => ['a', 'b', 'c', 'd']` - correct answer is `'abcd'`,
- `('a'...'d').inject(:+) => ['a', 'b', 'c']` - correct answer is `'abc'`,
- `(1..4).inject(10, :+) => [10, 1, 2, 3, 4]` - correct answer is `20`,
- `(1...4).inject(10, :+) => [10, 1, 2, 3]` - correct answer is `16`,
- `('a'..'d').inject('e', :+) => ['e', 'a', 'b', 'c', 'd']` - correct answer is `'eabcd'`,
- `('a'...'d').inject('e', :+) => ['e', 'a', 'b', 'c']` - correct answer is `'eabc'`

It looks like the examples outside of codeblocks should just be deleted, since they give incorrect versions of the examples in the codeblocks?

This problem is repeated under the entry for #reduce, an alias for #inject, where the entry and example is mostly repeated, except some of the signatures are omitted (which was confusing).
https://ruby-doc.org/3.2.2/Enumerable.html#method-i-reduce

I skimmed the rest of the Enumerable doc and did not see this problem in any other entries, of examples outside of codeblocks.

**Comment by nobu** [comment]
It says:
> If argument `initial_operand` is not given, the operands for +inject+ are simply the elements of +self+. Example calls and their operands:

That means `(1..4).inject(:+)` is equivalent to `[1, 2, 3, 4].inject(:+)`, not the former returns that array.

**Comment by MatheusRich** [comment]
Also, the examples don't contain the `=>` token, often used to represent return values. Can we close this?

<img width="474" alt="image" src="https://github.com/ruby/rdoc/assets/20938712/3786a272-5c66-4e57-b570-e6524f954f74">
