### ISSUE TITLE
`bundle exec rake rdoc` generates `Racc` document for RDoc

### ISSUE THREAD

**Issue by okuramasafumi** [ruby/rdoc#1159]
![CleanShot 2024-08-20 at 22 39 22@2x](https://github.com/user-attachments/assets/e6668392-7852-4c82-9e0d-b7507f97c289)

A document generated by `bundle exec rake rdoc` in RDoc repository includes `Racc` inside "Class and Module index". It's weird that references to `Racc` class seem not to exist.
I've looked through source code but didn't find any clue.

**Comment by olleolleolle** [comment]
What if... #1156 was used, and you tried again, would it happen, then, too?

**Comment by st0012** [comment]
It's generated because `Racc` will be included in generated files like `lib/rdoc/rd/block_parser.rb`.
