### ISSUE TITLE
Check new colour schemes are accessible for people with colour vision deficiencies

### ISSUE THREAD

**Issue by eightbitraptor** [ruby/rdoc#1196]
[Sim Daltonism](https://michelf.ca/projects/sim-daltonism/) or similar tools can be used to visually inspect and verify what web pages look like to folks with various forms of colour vision deficiency.

It would be good to check the new themes frequently during their development to make sure that the colour symbolism used matches the authors intent, when viewed by people with colour vision deficiencies.

**Comment by colby-swandale** [comment]
We have noted this and are working on a new permanent color scheme with accessibility in mind. Let's have a discussion in #1164
