### ISSUE TITLE
Method names sorted by ASCII code causes `~` and `|` to be placed at the bottom

### ISSUE THREAD

**Issue by peterzhu2118** [ruby/rdoc#1204]
Since the ASCII codes for `~` and `|` are greater than the alpha character codes, they are placed at the bottom of the method list compared to other operators such as `!`, `+`, or `%`. This is a bit odd as these two characters end up not grouped with the other operators.

For example, for [Integer documentation](https://docs.ruby-lang.org/en/master/Integer.html), we can see that most of the operator methods are at the top:

<img width="278" alt="Screenshot 2024-11-11 at 11 18 40 AM" src="https://github.com/user-attachments/assets/d602f984-5c2f-4fd7-b3ec-cb2b7e3d0461">

But there are two operators at the bottom:

<img width="293" alt="Screenshot 2024-11-11 at 11 19 08 AM" src="https://github.com/user-attachments/assets/1eac003c-f67b-488c-955b-7987a732a7ed">

**Comment by flavorjones** [comment]
Opened #1219 to address this.

**Comment by peterzhu2118** [comment]
Thanks @flavorjones @st0012 for fixing this!

**Comment by BurdetteLamar** [comment]
There are other lists of methods that suffer similarly; in particular, lists in some "What's Here" sections.  I'll look into fixing them.
