### ISSUE TITLE
Allow projects to disable auto-linking on certain words

### ISSUE THREAD

**Issue by st0012** [ruby/rdoc#1254]
https://github.com/ruby/ruby/pull/12451 introduced the top-level `Ruby` constant, which means that every `Ruby` in https://docs.ruby-lang.org/en/master/index.html are now linked to it:

<img width="60%" alt="Screenshot 2024-12-25 at 12 00 39" src="https://github.com/user-attachments/assets/2c9a613a-b1e5-4d75-bdd7-6e4d3aa09cde" />

Instead of escaping them one by one (there are more than a thousand occurrences in `ruby/ruby`), RDoc should allow projects to list a set of words that should not be auto-linked.

**Comment by ParadoxV5** [comment]
`Set` is another common word.
---
I wonder, what was the decision to autolink constants in the first place?

**Comment by st0012** [comment]
> Set is another common word.

Good call.

> I wonder, what was the decision to autolink constants in the first place?

I don't know as I wasn't the maintainer back then. But IMO for `ruby/ruby`, the biggest project using RDoc, this decision makes sense as it saves a lot of linking syntax when writing core component docs.

**Comment by skipkayhil** [comment]
Rails would definitely find this useful as well, we currently do the escaping manually 🙈 

https://github.com/rails/rails/blob/c31cc0b2e451b9271bdfedc68884e8ae38a7c0fb/actionview/lib/action_view/base.rb#L102-L103

**Comment by st0012** [comment]
PR: https://github.com/ruby/rdoc/pull/1259
