### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by ghost** [ruby/rdoc#175]
$ gem install pry
Fetching: coderay-1.0.8.gem (100%)
Fetching: slop-3.4.3.gem (100%)
Fetching: method_source-0.8.1.gem (100%)
Fetching: pry-0.9.11.4.gem (100%)
Successfully installed coderay-1.0.8
Successfully installed slop-3.4.3
Successfully installed method_source-0.8.1
Successfully installed pry-0.9.11.4
4 gems installed
Installing ri documentation for coderay-1.0.8...
Installing ri documentation for slop-3.4.3...
Installing ri documentation for method_source-0.8.1...
Installing ri documentation for pry-0.9.11.4...

RDoc::Parser::Ruby failure around line 25 of
lib/pry/commands/ls.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /home/myaccount/.rvm/rubies/ruby-1.9.3-p374/bin/ruby -c lib/pry/commands/ls.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

```
(NoMethodError) undefined method `name' for #<RDoc::RubyToken::TkDOT:0x00000003619bc8>
```

ERROR:  While generating documentation for pry-0.9.11.4
... MESSAGE:   undefined method `name' for #RDoc::RubyToken::TkDOT:0x00000003619bc8
... RDOC args: --ri --op /home/myaccount/.rvm/gems/ruby-1.9.3-p374/doc/pry-0.9.11.4/ri lib --title pry-0.9.11.4 Documentation --quiet

**Comment by sara-02** [comment]
one can also do gem install jekyll  --no-rdoc --no-ri.
Credits: http://stackoverflow.com/questions/9562582/issue-occuring-while-installing-gem

**Comment by cyofeiyue** [comment]
on the Mac OSX EI Captin platform,
Installing RDoc with `sudo gem install doc` fixed the issue too.
