### ISSUE TITLE
Regexp literal backslash getting stripped 

### ISSUE THREAD

**Issue by Neurogami** [ruby/rdoc#338]
Run rdoc over enum.c

The comments in the source code have this:

```
 e = lines.slice_after(/(?<!\\)\n\z/)
```

but the resulting rdoc output has this:

```
e = lines.slice_after(/(?<!\)\n\z/)
```

Note the missing backslash after the exclamation point.

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/rdoc/pull/471.
