### ISSUE TITLE
rdoc + darkfish + dry-run aborts

### ISSUE THREAD

**Issue by rovf** [ruby/rdoc#357]
The command

```
rdoc --dry-run --root=lib --format=darkfish --op=rdocs
```

aborts with 

```
 No such file or directory @ rb_sysopen - /home/FISRONA/gitwrk/vp5/rdocs/js/search_index.js
```

unless directory rdocs already contains files from a previous generation. It seems that --dry-run doesnt anticipate, that these intermediate directories will be generated in time.

Using rdoc 4.2.0 (Cygwin)

**Comment by zzak** [comment]
Ahh, interesting.. although I cannot reproduce it, I wonder if this is related to #334 based on the file mentioned in your backtrace.

Could you still reproduce it with a full backtrace? Thanks!

**Comment by rovf** [comment]
Run it again with --debug (I guess this is sufficient for getting full backtraced?):

Compressing generated JSON index
Reading the JSON index file from /home/FISRONA/gitwrk/playground/rdocs/js/search_index.js
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/FISRONA/gitwrk/playground/rdocs/js/search_index.js
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `read'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `read'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `generate_gzipped'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/darkfish.rb:249:in `generate'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:530:in `block in generate'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:525:in `chdir'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:525:in `generate'
  /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:508:in `document'
  /usr/share/gems/gems/rdoc-4.2.0/bin/rdoc:20:in `<top (required)>'
  /usr/bin/rdoc:23:in `load'
  /usr/bin/rdoc:23:in `<main>'
No such file or directory @ rb_sysopen - /home/FISRONA/gitwrk/playground/rdocs/js/search_index.js
/usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `read'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `read'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/json_index.rb:167:in `generate_gzipped'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/generator/darkfish.rb:249:in `generate'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:530:in `block in generate'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:525:in `chdir'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:525:in `generate'
        /usr/share/gems/gems/rdoc-4.2.0/lib/rdoc/rdoc.rb:508:in `document'
        /usr/share/gems/gems/rdoc-4.2.0/bin/rdoc:20:in `<top (required)>'
        /usr/bin/rdoc:23:in `load'
        /usr/bin/rdoc:23:in `<main>'

**Comment by zzak** [comment]
Thank you! I'll see if I can debug this backtrace and make a reproduction.
