### ISSUE TITLE
rdoc creates links for nonexisting modules / namespaces (eg: ActionController::ActionController::ActionController)

### ISSUE THREAD

**Issue by tphyahoo** [ruby/rdoc#364]
Link for ActionController::ActionController::ActionController (repeated 3 times) is created at

http://api.rubyonrails.org/classes/ActionController/ActionController/ActionController.html

IIUC, there is no such module or namespace. 

Repeated 2 times is also created at

http://api.rubyonrails.org/classes/ActionController/ActionController.html

(and points to repeated 3 times.)

**Comment by tphyahoo** [comment]
and here's a screenshot of the invalid nav on api.rubyonrails.org:

https://dl.dropboxusercontent.com/spa/5s4zfi0no72qeqw/th3hslt6.png

**Comment by zzak** [comment]
Thanks for filing the report!

**Comment by aycabta** [comment]
OK, this is the same reporting of https://github.com/ruby/rdoc/issues/516 what has small reproducible code, and I wrote explanation a little more at https://github.com/zzak/sdoc/issues/88#issuecomment-327409411. I'll fix it later.

**Comment by aycabta** [comment]
This fixed by https://github.com/ruby/rdoc/pull/523.
