### ISSUE TITLE
Bug when handling comments in C code examples

### ISSUE THREAD

**Issue by stomar** [ruby/rdoc#402]
_I already filed the following issue for ruby trunk (https://bugs.ruby-lang.org/issues/12258), but I guess here is the more appropriate place._

RDoc fails to correctly convert documentation that includes C example code with `/* ... */` comments.

It does not only produce wrong output for the comment itself (stripping the `/*` and `*/`), but also gets confused with occurences of `*` in completely different parts of the documentation, so that e.g. lists are displayed as code blocks. It appears that `*` at the very beginning of a line triggers a code block under these circumstances.

This affects e.g. http://docs.ruby-lang.org/en/trunk/extension_rdoc.html#label-Check+Data+Type+of+the+VALUE (partially stripped `/*` and `*/` from code example) or http://docs.ruby-lang.org/en/2.2.0/README_EXT.html#label-Adding+New+Features+to+Ruby (list displayed as code block); note that the broken list is fixed in trunk (it's rather a workaround) by using `-` instead of `*` for the list items.

Minimal example for a pure rdoc page:

```
$ cat broken_page.rdoc
A list:

* item 1
* item 2

A sentence with *emphasis* directly at the
*start* of a line.

Some example C code with comment:

  void
  do_something(VALUE val)
  {
    /* comment */
  }
```

For this rdoc produces:

A list:

```
item 1
item 2
```

A sentence with **emphasis** directly at the

```
start* of a line.
```

Some example C code with comment:

```
void
do_something(VALUE val)
{
     comment   
}
```

When generating rdoc of a Ruby class, the bug affects only the code example itself:

```
$ cat broken.rb 
# A class with broken rdoc.
#
# A list:
#
# * item 1
# * item 2
#
# A sentence with *emphasis* directly at the
# *start* of a line.
#
# Some example C code with comment:
#
#   void
#   do_something(VALUE val)
#   {
#     /* comment */
#   }
#
class Broken
end
```

This produces:

A class with broken rdoc.

A list:
- item 1
- item 2

A sentence with **emphasis** directly at the **start** of a line.

Some example C code with comment:

```
void
do_something(VALUE val)
{
     comment   
}
```

**Comment by jeremyevans** [comment]
I've checked and this bug has been fixed at some point.  RDoc now generates the following HTML:

.rdoc file:

```html
<p>A list:</p>
<ul><li>
<p>item 1</p>
</li><li>
<p>item 2</p>
</li></ul>

<p>A sentence with <strong>emphasis</strong> directly at the <strong>start</strong> of a line.</p>

<p>Some example C code with comment:</p>

<pre>void
do_something(VALUE val)
{
  /* comment */
}</pre>
```

Class comment in .rb file:

```html
<p>A class with broken rdoc.</p>

<p>A list:</p>
<ul><li>
<p>item 1</p>
</li><li>
<p>item 2</p>
</li></ul>

<p>A sentence with <strong>emphasis</strong> directly at the <strong>start</strong> of a line.</p>

<p>Some example C code with comment:</p>

<pre>void
do_something(VALUE val)
{
  /* comment */
}</pre>
```
