### ISSUE TITLE
unexpected document injection on 5.0.0.beta2

### ISSUE THREAD

**Issue by hsbt** [ruby/rdoc#422]
https://gist.github.com/k-tsj/9f58f29643067b2b1cb32a8ab3defde3

**Comment by hsbt** [comment]
It happened with Ruby 2.3.1 with rdoc 4.2.1

**Comment by sho-h** [comment]
ruby/docs.ruby-lang.org#40 happened with Ruby 2.3.3 with rdoc 5.1.0.
Ruby 2.3.3 is using Debian Stretch package.
rdoc 5.1.0 is installed by bundler.

**Comment by sho-h** [comment]
Maybe, rdoc 5.1.0 has 2 bugs and 1 old code to see this problem.

1. RDoc::RubyToken::Symbol was parsed as Integer. And ts name was Symbol.
    * :stopdoc: was ignoring?
2. RDoc::NormalClass#name was invalid for RDoc::RubyToken::Symbol at lib/rdoc/ruby_token.rb
    * keys of @classes_hash in RDoc::Store was correct.
3. lib/rdoc/ruby_token.rb has for obsoleted Ruby code. (see #527)

**Comment by aycabta** [comment]
Please check RDoc 6.0 at master branch because RDoc 6.0 what will be released soon [has very many changes](https://github.com/ruby/rdoc/pulls?utf8=%E2%9C%93&q=is%3Aclosed%20is%3Apr%20author%3Aaycabta%20sort%3Aupdated-desc%20merged%3A%3C2017-09-16%20).

But I grasp what the same problem still occors at 6.0. I'll check this issue later.

> lib/rdoc/ruby_token.rb has for obsoleted Ruby code.

I know, but `lib/rdoc/ruby_token.rb` will be removed and it's unnecessary at 6.0.

**Comment by sho-h** [comment]
Sorry, I misunderstood this issue is same problem with invalid https://docs.ruby-lang.org/en/2.4.0/Symbol.html problem.

> But I grasp what the same problem still occors at 6.0. I'll check this issue later.
> ...
> I know, but lib/rdoc/ruby_token.rb will be removed and it's unnecessary at 6.0.

Thanks. Symbol.html will correct at 6.0, I glad. But I want fix this problem soon...
Maybe, I will take workaround on docs.ruby-lang.org.

**Comment by hsbt** [comment]
This is an expected behavior.

And I confirmed to fix at Ruby 2.5.0. Current BigDecimal documentation treats Open class document. see https://github.com/ruby/ruby/blob/trunk/ext/bigdecimal/lib/bigdecimal/util.rb#L51

**Comment by hsbt** [comment]
In Japanese: @aycabta と確認したんですが、RDoc が混ざるのは期待した動きで、たまたま BigDecimal の rdoc ドキュメントが String で最初のセクションにさしこまれるので、ユーザーにとっては混乱するということのようです。

これを rdoc の機能としていい感じにするというのはなかなか難しいのですが、Ruby 2.5.0 の BigDecimal では、BigDecimal 側で String に対するドキュメントは削られており、混乱するような出力にはなってませんでした。

現在の実装の結論としては、いい感じの出力となるようにドキュメントを書く側が頑張る、という感じです。
