### ISSUE TITLE
Incorrect alias names are shown

### ISSUE THREAD

**Issue by Neurogami** [ruby/rdoc#429]
See, for example,  the rdocs for Queue: https://docs.ruby-lang.org/en/2.3.0/Queue.html

The `size `method is shows 

```
Alias for pop.
Alias for: length
```

But `pop `has nothing to do with `size`.   There are other similar mismatched aliases on that doc page (deq, for example).

In this example the aliasing is defined in `thread_sync.c`.   

If you change the order of the aliasing some of these inappropriate alias listing go away.

**Comment by aycabta** [comment]
I reported at [ruby-core#14354](https://bugs.ruby-lang.org/issues/14354).
