### ISSUE TITLE
:arg:, :args: doesn't work.

### ISSUE THREAD

**Issue by tonytonyjan** [ruby/rdoc#433]
[The example from rdoc document](http://docs.seattlerb.org/rdoc/RDoc/Markup.html#class-RDoc::Markup-label-Method+arguments) doesn't work:

```ruby
##
#  :args: a, b

def some_method(*a)
end
```

But it works inline:

```ruby
def some_method(*a) # :args: a, b
end
```

My rdoc version is 5.0.

**Comment by aycabta** [comment]
OK, it's reproduced if RDoc 6.0.0.beta2. I'll check this bug later.
