### ISSUE TITLE
Class content with :nodoc: cause all file to be skipped

### ISSUE THREAD

**Issue by Paxa** [ruby/rdoc#437]
I found this bug in minitest's docs. (https://github.com/seattlerb/minitest/issues/674)

Small example:
```ruby
# Docs for my class
module MyClass

  # This method will be shown
  def foo
    
  end

  class << self; attr_accessor :io_lock; end # :nodoc:

  # This method will be skipped
  def this_method_not_appear
    do_something()
  end

end
```

Will be rendered as:
![screen shot 2017-01-05 at 9 32 37 pm](https://cloud.githubusercontent.com/assets/26019/21682246/87c21be6-d38e-11e6-8651-cf2157190e68.png)

**Comment by aycabta** [comment]
It's fixed on RDoc 6.0.0.beta2 at least.
