### ISSUE TITLE
Convert links in md files

### ISSUE THREAD

**Issue by ArtsiomMusin** [ruby/rdoc#442]
I have a question if it's possible somehow to convert a link which points to another md file.
Here is an example. Let's suppose I have README.md which has this:
`Some text here [LINK](build_steps.md)`

After I run 'rdoc', I get two files: README_md.html and build_steps_md.html.
However, README_md.html has something like:
`<p>Some text here <a href="build_steps.md">LINK<a><p>`
The link points to the .md file, but we've got only the _md.html one.

So is that possible to convert md links to html ones? Did I missed an option to do that?

**Comment by aycabta** [comment]
Please use `[LINK](build_steps)`. You don't need an extension to make a link.
