### ISSUE TITLE
Bullet points of 6.0 changes for CRuby's ChangeLog

### ISSUE THREAD

**Issue by aycabta** [ruby/rdoc#504]
Let me write later.

**Comment by aycabta** [comment]
- Remove offset from CodeObject
- Support rational and imaginary
- Support hash rocket "=>"
- Fix seeking position when parses symbol
- Handle "[]" and "[]=" after "." as method
- Handle JSON-style hash key as symbol
- Handle dynamic regexp token as regexp in HTML
- Handle "#{}" as dynamic string
- Handle redefinable operators as identifier
- Stop dropping continuing backslash
- Support %i and %I literal
- Fix for "\n" after backslash escape
- Fix escape in string
- Fix backtick handling
- Support lambda literal
- Fix handling hash rocket after symbol
- Fix percent string literal with operator
- Fix heredoc
- Fix complex condition in for/while/until
- Fix n-ary detecting condition for rational and imaginary
- Handle constant ending with "!" as identifier
- Fix postfix "if" after escaped newline
- Fix postfix if/unless/while/until after heredoc
- Fix escape behavior in single quote string literal
- Support safe navigation operator
- Fix creation of symbol token for reserved keywords and others
- Separate "foo!=bar" to "foo", "!=" and "bar"
- Fix  assignment operator
- Fix for symbol detection when nesting method
- Support escaped character literal
- Fix handling symbol args of yield/super/defined?
- Fix handling embdoc and unnecessary blank line in <pre>
- Handle number with plus or minus sign as integer
- Fix postfix :nodoc:
- Fix regexp literal in one-liner
- Support quoted symbol key for JSON-style hash literal
- Handle __ENCODING__ as keyword
- Fix % literal with the same sign of original
- Context#each_section yields only #display? items
- Support multi-line constant body with escaped newline
- Use IO.console.winsize instead of IO.console_size for JRuby 9k
- Fix constant assignment as alias with Hash
- Fix handling "rescue" inside paren
- Fix JSON-style Hash literal for args of method
- Use Ripper for lexical analyzer
- Skip the same of outside nesting namespace
- Fix variable expansion in args of yield
- Escape yield parameters
- Fix CodeFence of markdown.kpeg with unintended Array for format
- Support did_you_mean
- Support :args: directive before method
- Handle all definitions per file in Ruby
- Use "frozen_string_literal: true"
- Add ruby-title class to method name in HTML
- Update markdown.kpeg from upstream
- Use Enumerable#chunk after drop Ruby 1.8
- Use ParseError that is auto-generated by KPeg

**Comment by aycabta** [comment]
@hsbt Do you need other people's implementations?

**Comment by aycabta** [comment]
Squashed:

- Replaced IRB based lexer with Ripper.
    - https://github.com/ruby/rdoc/pull/512
    - It much improves the speed of generating documents.
    - To facilitate supporting new syntax in the future.
- Supported many new syntaxes of Ruby in the past few years.
- Used "frozen_string_literal: true". It reduces documents generation time by 5%.
- Supported did_you_mean.

**Comment by hsbt** [comment]
Thanks a lot. I've committed at https://github.com/ruby/ruby/commit/71e5c125783c1ac85a1c5cea6926473e43fd015c
