### ISSUE TITLE
Test fail with non-tty environment

### ISSUE THREAD

**Issue by hsbt** [ruby/rdoc#517]
@aycabta 

Ruby CI detects a broken code with rdoc-6.0.0.beta2.

https://rubyci.org/logs/rubyci.s3.amazonaws.com/ubuntu1604/ruby-trunk/log/20170912T093009Z.fail.html.gz

`IO.console` is not provided non-tty environment like cron job. I reverted 8cfa11d6f1cc7e74e45e42fd8d1d76c5a0646a6e

Maybe, We should skip related tests with JRuby.

**Comment by aycabta** [comment]
I understand what you explained, thank you for fixing bug what I made by https://github.com/ruby/rdoc/pull/518.
