### ISSUE TITLE
(RDoc::RubyLex::Error) Missing terminating xx for string (rdoc-5.1.0/lib/rdoc/ruby_lex.rb:1026:in `identify_here_document')

### ISSUE THREAD

**Issue by knut2** [ruby/rdoc#558]
When I try to use rdoc with the following code:

    var = ''
    var <<'xx'

then I get an error: 

    RDoc::Parser::Ruby failure around line 6 of
    test_rdoc_error.rb
    ....
    Before reporting this, could you check that the file you're documenting
    has proper syntax:

      ruby.exe -c test_rdoc_error.rb

    RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

    The internal error was:

      (RDoc::RubyLex::Error) Missing terminating xx for string

The error must be anywhere around `rdoc-5.1.0/lib/rdoc/ruby_lex.rb:1026`.

The rdoc parser does interprete the `<<'xx'` as a here-document, but in this case it concatenates a string to another string.

This problem disappears, when I add a space between the `<<` and the String in `var <<'xx'` or if there is any character after the `var <<'xx'`. 

So it can be solved quite easy in your code.  But I was surprised, when I tried to make a documentation of my working code and needed some time to detect the problem.

**Comment by aycabta** [comment]
Thank you for your reporting. RDoc 6 what uses Ripper for lexical analysis solves it and is released soon. Please wait for it.
