### ISSUE TITLE
fix reset order.

### ISSUE THREAD

**Issue by ko1** [ruby/rdoc#578]
Please check https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=61521
Ruby trunk fixed this issue.

**Comment by aycabta** [comment]
I got the picture about the patch and cherry-pick-ed https://github.com/ruby/ruby/commit/fb112a8c4debb4220eaa5a75fbb10afb39672b20 to https://github.com/ruby/rdoc/commit/9405d8686772fbecec5b25e328fe046813f7bd3e.
