### ISSUE TITLE
--exclude does not work properly

### ISSUE THREAD

**Issue by voxik** [ruby/rdoc#596]
Trying to exclude some parts of the documentation, it seems that the ```--exclude``` option does not work properly. E.g. trying to generate documentation for Ruby StdLib excluding rubygems:

~~~
$ rdoc --op ./foo --encoding=UTF-8 --all --ri -x rubygems /var/lib/mock/ruby/root/builddir/build/BUILD/ruby-2.5.0/lib | grep rubygems
 45% [154/337]  /var/lib/mock/ruby/root/builddir/build/BUILD/ruby-2.5.0/lib/rdoc/rubygems_hook.rb
 78% [263/337]  /var/lib/mock/ruby/root/builddir/build/BUILD/ruby-2.5.0/lib/rubygems.rb

Generating RI format into /home/vondruch/ff/foo...

... snip ...
~~~

Although this excludes the lib/rubygems directory, it keeps other "rubygems" files. Trying exclude "rdoc", it does not even exclude the "rdoc" directory.

~~~
$ rdoc -v
6.0.1

$ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
~~~

**Comment by aycabta** [comment]
The directory has [`.document` file](https://github.com/ruby/ruby/blob/v2_5_0/lib/.document) what has priority over `--exclude` option. I think that the behavior is a bug. I fixed it by https://github.com/ruby/rdoc/pull/603.
