### ISSUE TITLE
block comment delimiters are in the documentation

### ISSUE THREAD

**Issue by mariusz-kowalski** [ruby/rdoc#600]
If I use block comment, `=begin` and `=end` delimiters are part of the documentation, and they are interpreted as headings `h1`:

example_class.rb
```ruby
=begin
This is documentation
=end
class ExampleClass; end
```
This
```sh
rdoc example_class.rb
```
will generate the documentation with heading (h1) "begin" at the beginning and heading "end" at the end.

```html
<h1 id="class-ExampleClass" class="class">
  class ExampleClass
</h1>
<section class="description">
  <h1 id="class-ExampleClass-label-begin">
    begin
    <span><a href="#class-ExampleClass-label-begin">¶</a> <a href="#top">↑</a></span>
  </h1>

  <p>This is documentation</p>

  <h1 id="class-ExampleClass-label-end">
    end
    <span><a href="#class-ExampleClass-label-end">¶</a> <a href="#top">↑</a></span>
  </h1>
</section>
```
`=begin` and `=end` are just comment delimiters and should not be a part of the documentation.

I'm using version 6.0.1 (ruby 2.5)

**Comment by topofocus** [comment]
Same feature here. 
Is there a known walk around?

Worst: »begin» and »end» are included in  /rdoc/table_of_contents.html#classes
