### ISSUE TITLE
clicked selenium-webdriver-3.11.0 [rdoc],finded a error! who can tell me why?

### ISSUE THREAD

**Issue by lihuoxiu** [ruby/rdoc#607]
Error
While processing http://localhost:8808/doc_root/selenium-webdriver-3.11.0/ the RDoc (6.0.1) server has encountered a NoMethodError exception:

undefined method `path=' for #<WEBrick::HTTPRequest:0x0358bc78>
Did you mean?  path
Please report this to the RDoc issues tracker. Please include the RDoc version, the URI above and exception class, message and backtrace. If you're viewing a gem's documentation, include the gem name and version. If you're viewing Ruby's documentation, include the version of ruby.

Backtrace:

E:/selenium2_ruby/selenium2_ruby_03/Ruby25/lib/ruby/2.5.0/rdoc/servlet.rb:114:in `do_GET'
E:/selenium2_ruby/selenium2_ruby_03/Ruby25/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:105:in `service'
E:/selenium2_ruby/selenium2_ruby_03/Ruby25/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
E:/selenium2_ruby/selenium2_ruby_03/Ruby25/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
E:/selenium2_ruby/selenium2_ruby_03/Ruby25/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

**Comment by aycabta** [comment]
I guess that this is the same bug of https://github.com/ruby/rdoc/issues/587. It was fixed. I released RDoc 6.0.2 now. Please check it!
