### ISSUE TITLE
Convert links to local files in markdown

### ISSUE THREAD

**Issue by znz** [ruby/rdoc#618]
Original issue is [Some links broken in README ](https://github.com/ruby/docs.ruby-lang.org/issues/56).
I found two problem.

1. `COPYING`, `CONTRIBUTING.md`, etc. are not in <https://docs.ruby-lang.org/en/trunk/>.
2. links to local files in markdown do not convert to links to converted html files.

[I added missing files to `.document`](https://github.com/ruby/ruby/commit/342709d18763d91ad196f62186bb8752ecba2b56), but they are still broken links because rdoc does not convert links to local files.

**Comment by aycabta** [comment]
The [`README.md` uses link notation](https://github.com/ruby/ruby/commit/49f17cc6a36ca0044dd8672c4d9246f692bffaf9).

```markdown
## Contributing

See the file [CONTRIBUTING.md](CONTRIBUTING.md)
```

I guess that this is just for GitHub and I think that RDoc's behavior is correct. You can use `rdoc-ref`([example](https://github.com/ruby/ruby/blob/96db72ce38b27799dd8e80ca00696e41234db6ba/doc/syntax.rdoc), [raw](https://raw.githubusercontent.com/ruby/ruby/96db72ce38b27799dd8e80ca00696e41234db6ba/doc/syntax.rdoc) and [generated](https://docs.ruby-lang.org/en/trunk/syntax_rdoc.html)).

**Comment by aycabta** [comment]
Just to be safe, please use `rdoc-ref` without extension. For example, `[CONTRIBUTING.md](CONTRIBUTING)`.

**Comment by znz** [comment]
`[COPYING](COPYING)` and `[win32/README.win32](win32/README.win32)` are without extension.
Should they be `[COPYING](rdoc-ref:COPYING)` and `[win32/README.win32](rdoc-ref:win32/README.win32)`?
Is there no way to generate valid link on github and rdoc generated html?

**Comment by aycabta** [comment]
You can use `[COPYING](rdoc-ref:COPYING)`, but `[win32/README.win32](rdoc-ref:win32/README.win32)` is failed. I guess this is a bug, so I'll survey this issue later.

We can't generate valid links for both of GitHub UI and HTML files by Darkfish. Is it important? I think that GitHub's UI isn't important for Ruby. And, I don't want to optimize RDoc for GitHub.
