### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by janko-m** [ruby/rdoc#621]
I'm pulling my .md files through RDoc generation, and there is a code block that fails to be syntax highlighted:

```rb
Dragonfly.app
  .fetch_url(photo.image_url) # image uploaded by Shrine
  .thumb("800x800")
  .url #=> "/attachments/W1siZnUiLCJodHRwOi8vd3d3LnB1YmxpY2RvbWFpbn..."
```

If I remove the `# image uploaded by Shrine` comment, the code is properly highlighted.

**Comment by aycabta** [comment]
I couldn't reproduce the behavior with a code below. I confirmed that both syntax-highlighted-codes, a document for `Foo#bar` and source code of `Foo#bar`.

```ruby
class Foo
  ##
  # This is document.
  #
  #   Dragonfly.app
  #     .fetch_url(photo.image_url) # image uploaded by Shrine
  #     .thumb("800x800")
  #     .url #=> "/attachments/W1siZnUiLCJodHRwOi8vd3d3LnB1YmxpY2RvbWFpbn..."
  #
  def bar
    Dragonfly.app
      .fetch_url(photo.image_url) # image uploaded by Shrine
      .thumb("800x800")
      .url #=> "/attachments/W1siZnUiLCJodHRwOi8vd3d3LnB1YmxpY2RvbWFpbn..."
  end
end
```

![syntax highlighted page capture](https://i.gyazo.com/4ad8e27ff59a6eb6d04b9696415c4fb1.png)

Please show your RDoc version and more detailed situation.

**Comment by aycabta** [comment]
@janko-m Can you reproduce this issue on latest RDoc?

**Comment by janko-m** [comment]
Thanks a lot of following up!

I tried now going back to the version of my document where the syntax highlighting was broken in the RDoc output, but now the output is correct. It must be that the new `rdoc` fixed it 😃
