### ISSUE TITLE
Use of include with anonymous module with method breaks further parsing

### ISSUE THREAD

**Issue by jeremyevans** [ruby/rdoc#627]
This issue occurs when you have a `include` or `extend` method call inside a class/module, and an argument inside `include` or `extend` that uses a block, and define a method with parentheses inside the block. In such cases, future classes (`A::C` and `A::D` in the examples below) are missed by the parser.

Example failing code:

```ruby
module A
  class B
    include(Module.new do
      def e(m)
      end
    end)
  end

  class C
  end

  class D
  end
end
```

Removing the parentheses when defining the method is sufficient to work around this bug:

```ruby
module A
  class B
    include(Module.new do
      def e m 
      end
    end)
  end

  class C
  end

  class D
  end
end
```

As is using a local variable for the `Module.new` result and passing that to include:

```ruby
module A
  class B
    m = Module.new do
      def e(m)
      end
    end
    include m
  end

  class C
  end

  class D
  end
end
```

Here's another failing case showing the problem is not related to `Module.new` or `do`/`end` vs `{`/`}`:

```ruby
module A
  class B
    extend(e {
      def f(g)
      end
    })
  end

  class C
  end

  class D
  end
end
```

**Comment by jeremyevans** [comment]
Note that when using `{`/`}` instead of `do`/`end`, instead of not picking up the classes, the parser picks up `A::C` as `C` and `A::D` as `D`.

**Comment by aycabta** [comment]
@jeremyevans Thank you for your reporting!
