### ISSUE TITLE
Error - NoMethodError

### ISSUE THREAD

**Issue by JohnnyMorbo** [ruby/rdoc#641]
Error

While processing http://localhost:8808/doc_root/mysql2-0.4.10/ the RDoc (6.0.1) server has encountered a NoMethodError exception:

undefined method `path=' for #<WEBrick::HTTPRequest:0x00007fb1f0187d20>
Did you mean?  path

Please report this to the RDoc issues tracker. Please include the RDoc version, the URI above and exception class, message and backtrace. If you're viewing a gem's documentation, include the gem name and version. If you're viewing Ruby's documentation, include the version of ruby.

Backtrace:

/usr/lib64/ruby/2.5.0/rdoc/servlet.rb:114:in `do_GET'
/usr/lib64/ruby/2.5.0/webrick/httpservlet/abstract.rb:105:in `service'
/usr/lib64/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib64/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib64/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

openSUSE Tumbleweed repos
RDoc 6.0.1
http://localhost:8808/doc_root/mysql2-0.4.10/
mysql2 0.4.10
ruby 2.5.0

**Comment by mathieujobin** [comment]
Hey, how did you resolve it ? 
I am getting this same error ? 

ruby 2.5.3, every gems installed
I am using rvm and I ran `rvm docs generate-gems`

can't visit local docs 

thanks

**Comment by JohnnyMorbo** [comment]
@mathieujobin Sorry, I don't remember.  It was too long ago.
I kinda think it was a silly error on my part, and that's why I closed this within a few hours, but I don't remember what I did.
¯\_(ツ)_/¯
