### ISSUE TITLE
Trying to use rdoc in interactive ruby for ruby file

### ISSUE THREAD

**Issue by MDVACHON** [ruby/rdoc#691]
I am trying to use ‘rdoc’ to generate html documentation file for my code within the ruby interactive software , but it simply does not work. I have change the directory where the code file is located. I am writing ‘rdoc file_name.rb’. I am a beginner , but cannot seems to figure it out.

Please help!

**Comment by aycabta** [comment]
Please show me source code that reproduces the problem.

**Comment by MDVACHON** [comment]
I was able to make it work with Amazon AWS Cloud 9. Might of been something with the software I was using.  My code was the below. Very simple code.

class Person
    attr_accessor :name
    def introduction
        "Hello, my name is #{name}!"
    end
end

In the terminal, I made sure the directory was correct by writing "cd my_project" and after "rdoc person.rb". The html documentation was made all in the my_project folder. 

Thanks,
