### ISSUE TITLE
Failed to build ri for rgen gem

### ISSUE THREAD

**Issue by majioa** [ruby/rdoc#697]
In current HEAD, and 6.1.1, I have troubles with build ri documentation for the **rgen** gem in the file: *lib/rgen/ecore/ecore_to_ruby.rb*, it has good syntax:

    $ /usr/bin/ruby -c lib/rgen/ecore/ecore_to_ruby.rb
    Syntax OK

Trace log:

    $ rdoc --ri-site -o ri lib app config ext
        NoMethodError: undefined method `[]' for nil:NilClass
        /usr/lib/ruby/site_ruby/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?'
        /usr/lib/ruby/site_ruby/rdoc/parser/ripper_state_lex.rb:473:in `get_heredoc_tk'
        /usr/lib/ruby/site_ruby/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
        /usr/lib/ruby/site_ruby/rdoc/parser/ripper_state_lex.rb:578:in `parse'
        /usr/lib/ruby/site_ruby/rdoc/parser/ruby.rb:180:in `initialize'
        /usr/lib/ruby/site_ruby/rdoc/parser.rb:191:in `new'
        /usr/lib/ruby/site_ruby/rdoc/parser.rb:191:in `for'
        /usr/lib/ruby/site_ruby/rdoc/rdoc.rb:360:in `parse_file'
        /usr/lib/ruby/site_ruby/rdoc/rdoc.rb:416:in `block in parse_files'
        /usr/lib/ruby/site_ruby/rdoc/rdoc.rb:414:in `map'
        /usr/lib/ruby/site_ruby/rdoc/rdoc.rb:414:in `parse_files'
        /usr/lib/ruby/site_ruby/rdoc/rdoc.rb:483:in `document'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:61:in `documentate'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:50:in `block (2 levels) in exec_ri'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:49:in `chdir'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:49:in `block in exec_ri'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:48:in `each'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:48:in `exec_ri'
        /usr/lib/ruby/site_ruby/setup/documentor.rb:35:in `document'
        /usr/lib/ruby/site_ruby/setup/session.rb:168:in `document'
        /usr/lib/ruby/site_ruby/setup/session.rb:118:in `build'
        /usr/lib/ruby/site_ruby/setup/command.rb:112:in `run'
        /usr/lib/ruby/site_ruby/setup/command.rb:13:in `run'
        /usr/bin/setup.rb:28:in `<main>'

**Comment by dklotz** [comment]
Maybe related to #694? At least the error message is the same.
