### ISSUE TITLE
pg 0.9.0`s Rdoc

### ISSUE THREAD

**Issue by BuWare** [ruby/rdoc#704]
ruby 2.5.3p105 (2018-10-18 revision 65156) [i386-mingw32]
Rails 5.1.6.1

------------------------------------------------------------------------------------------------------
Error
While processing http://localhost:8808/doc_root/pg-0.9.0-x86-mingw32/ the RDoc (6.0.1) server has encountered a NoMethodError exception:

undefined method `path=' for #<WEBrick::HTTPRequest:0x04140990>
Did you mean?  path
Please report this to the RDoc issues tracker. Please include the RDoc version, the URI above and exception class, message and backtrace. If you're viewing a gem's documentation, include the gem name and version. If you're viewing Ruby's documentation, include the version of ruby.

Backtrace:

C:/Ruby25/lib/ruby/2.5.0/rdoc/servlet.rb:114:in `do_GET'
C:/Ruby25/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:105:in `service'
C:/Ruby25/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
C:/Ruby25/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
C:/Ruby25/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
------------------------------------------------------------------------------------------------------

**Comment by aycabta** [comment]
This is fixed by https://github.com/ruby/rdoc/commit/82d59dd0369155153701d96aa8c86cb77780b5ed so please use latest RDoc(v6.1.1).
