### ISSUE TITLE
This repository should contain canonical source for RI man page

### ISSUE THREAD

**Issue by voxik** [ruby/rdoc#717]
Ruby ships with RI man page:

https://github.com/ruby/ruby/blob/trunk/man/ri.1

But since this is upstream of RI, it would be nice if this repository was also upstream of that man page. Ideally if it was shipped with the packaged gem as well.

**Comment by yasuhirokimura** [comment]
+1

Please not only add ri(1) man page to this repository but also include it to next version of gem.

An example of gem that includes man pages are bundler. Hope this helps.
