### ISSUE TITLE
The History.rdoc file is out of sync

### ISSUE THREAD

**Issue by bbatsov** [ruby/rdoc#722]
Seems https://github.com/ruby/rdoc/blob/master/History.rdoc hasn't been updated in a long time. Same with https://github.com/ruby/rdoc/blob/master/TODO.rdoc

It'd be nice of recent improvements and current plans were reflected there.

**Comment by bbatsov** [comment]
I've also noticed that none of the releases (https://github.com/ruby/rdoc/releases) have any release notes.

**Comment by bbatsov** [comment]
Some context - Matz recently said at RubyKaigi that big improvements where coming to RDoc, but I've been struggling to figure out what exactly did he mean. :-) Some insight would be appreciated!

**Comment by hsbt** [comment]
👋  @bbatsov Sorry to late response.

I create the releases for old versions. We will create them in the future.
