### ISSUE TITLE
Cannot create link to unary operator methods

### ISSUE THREAD

**Issue by UlyssesZh** [ruby/rdoc#767]
```ruby
##
class RDocTest
  ##
  # I want to refer to #-@ the unary operator method.
  def -@
  end
end
```
Generate the doc using rdoc, and the hyperlink to `#-@` method is not created.

**Comment by hyrious** [comment]
Quickly looked into the source code and here comes my fix:
1. add `+@, -@` regex to https://github.com/ruby/rdoc/blob/78f3ce4057ded99c93a0924d67da5b9adbf97356/lib/rdoc/cross_reference.rb#L22
   ```diff
   -  METHOD_REGEXP_STR = '([a-z]\w*[!?=]?|%|===|\[\]=?|<<|>>|-|\+|\*)(?:\([\w.+*/=<>-]*\))?'
   +  METHOD_REGEXP_STR = '([a-z]\w*[!?=]?|%|===|\[\]=?|<<|>>|\+@|-@|-|\+|\*)(?:\([\w.+*/=<>-]*\))?'
   ```
2. exclude them from https://github.com/ruby/rdoc/blob/78f3ce4057ded99c93a0924d67da5b9adbf97356/lib/rdoc/markup/to_html_crossref.rb#L65 https://github.com/ruby/rdoc/blob/78f3ce4057ded99c93a0924d67da5b9adbf97356/lib/rdoc/markup/to_html_crossref.rb#L141
   ```diff
   -    if name =~ /(.*[^#:])@/
   +    if !(name.end_with?('+@', '-@')) and name =~ /(.*[^#:])@/
   ```
It just works. Not sure if it has further bugs.

**Comment by aycabta** [comment]
@UlyssesZh Thank you for this reporting. I found some broken links to unary operator methods in Ruby's official documents. This will help for users so much.

@hyrious It's a great patch. I created #778 with a commit you're the author of.

**Comment by aycabta** [comment]
@hyrious Congrats! [This is your first commit in Ruby repository](https://github.com/ruby/ruby/commits?author=hyrious)!
