### ISSUE TITLE
RDoc is not a full Ruby parser and will fail when fed invalid ruby programs. (parsing concern)

### ISSUE THREAD

**Issue by Pranay0302** [ruby/rdoc#786]
The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```
❯ rdoc -v
6.3.0 
```

**Comment by nobu** [comment]
What code did cause the error?

**Comment by Pranay0302** [comment]
```
sudo gem update

```

**Comment by nobu** [comment]
I mean that a message like the following should be printed before the message you pasted.

```
Before reporting this, could you check that the file you're documenting
has proper syntax:

  ruby -c something_wrong.rb

```

**Comment by Pranay0302** [comment]
yep, that part appeared.
I reinstalled rdoc and it works fine now without any errors.
```
sudo gem install rdoc
```
