### ISSUE TITLE
RDoc generation gets stuck and CPU is at 100%

### ISSUE THREAD

**Issue by spastorino** [ruby/rdoc#81]
More info here https://github.com/rails/rails/issues/3322

**Comment by mailinglists35** [comment]
Can this be related?
https://github.com/rails/rails/issues/11814
my "gem install" command is stuck consuming all cpu.

**Comment by drbrain** [comment]
Please open a new issue with details on where you are getting stuck.  Use the `--verbose` option to show RDoc parsing progress.
