### ISSUE TITLE
Bug on multiple inclusion for classes

### ISSUE THREAD

**Issue by BuonOmo** [ruby/rdoc#814]
I'm trying to fix completion (in irb) for https://github.com/rgeo/rgeo. However, I stumbled upon an issue which once reduced to a minimal example seems to be a `Rdoc` bug:

```ruby
# t.rb
module RGeo
  module Feature
    module Surface
      # YEAH YEAH YIPIYEAH YIPIYO
      def centroid
        puts "I can be executed"
      end
    end
  end
end

module RGeo
  module Feature
    module Polygon
      include Surface
    end
  end
end

module RGeo
  class Geos
    class CAPIPolygonImpl # changing that for `module Geos` works
      include Feature::Polygon
    end
  end
end
```

```bash
$ rdoc -q -f ri --op t t.rb
$ ri --no-standard-docs -d t RGeo::Geos::CAPIPolygonImpl#centroid
Nothing known about RGeo::Geos::CAPIPolygonImpl#centroid
```

The code is valid ruby (you never now ^^, `ruby -r./t.rb -e 'RGeo::Geos::CAPIPolygonImpl.new.centroid'`). And changing the `class CAPIPolygonImpl` to `module CAPIPolygonImpl` gives the expected output:

```bash
$ ri --no-pager --no-standard-docs -d t RGeo::Geos::CAPIPolygonImpl#centroid
RGeo::Geos::CAPIPolygonImpl#centroid

(from /Users/ulysse/Dev/rgeo/rgeo/t)
Implementation from Surface
------------------------------------------------------------------------
  centroid()

------------------------------------------------------------------------

YEAH YEAH YIPIYEAH YIPIYO
```

Do you have any hint on where it could come from?

Thank you 🙏

**Comment by Quiwin** [comment]
It seems to be an issue with `ancestors_of` https://github.com/ruby/rdoc/blob/ebe185c8775b2afe844eb3da6fa78adaa79e29a4/lib/rdoc/ri/driver.rb#L612
which break out of its loop if a class has no store associated to it.

When checking for associated store for the ancestor `Object`, no context is found because of `--no-standard-docs` and the loop break.
