### ISSUE TITLE
rdoc 6.4 breaks bundler for Rails 5

### ISSUE THREAD

**Issue by cooperka** [ruby/rdoc#857]
As of rdoc 6.4 (in commit https://github.com/ruby/rdoc/commit/ebe185c8775b2afe844eb3da6fa78adaa79e29a4), psych v4 is being requested which is a major breaking change because it does not support Ruby 2.5 and Rails 5 (see https://github.com/ruby/psych/issues/531 for documentation).

I can't find any sort of changelog or history doc for this repo since 2017, so maybe I'm in the wrong here -- did you intend to remove support for Rails 5 in v6.4? Happy to help submit whatever PR is necessary here if I can be of help.

---

EDIT: Fixed link to Psych issue.

**Comment by hsbt** [comment]
Yes. You can use psych 3.x for Rails 5. I wonder why you want to use psych 4 for the old version of Ruby and Rails.

**Comment by cooperka** [comment]
Hi @hsbt, I don't think you understand my issue report. The problem is that rdoc v6.4 has broken any similar Rails 5 installations. It should have been released as v7, and we can fix that quite easily.

If I submit a PR rolling back to the earlier code, to be released as v6.5, and simultaneously re-release v6.4 as v7, would you accept the PR?

**Comment by hsbt** [comment]
I'm not sure what you will request. Did you enforce to apply SemVer policy?

**Comment by cooperka** [comment]
I see, thanks for explaining that you don't follow SemVer.

It's important to document major changes like this for your users; this caused me hours of frustration because it wasn't clear what dependency caused the problem. I wouldn't expect a docs gem to break my entire app during a routine update.

If you don't want to follow version conventions, could we publish a changelog? Or could we add a note in the readme? I will submit a PR for whatever you will accept, please help me help your other users.

**Comment by hsbt** [comment]
[> this caused me hours of frustration because it wasn't clear what dependency caused the problem.

I see. But I and other maintainers are volunteers and work with spare time. We don't have enough time to write a document. I'm also frustrated by your order what development policy in Holiday time.

 

> If you don't want to follow version conventions, could we publish a changelog? Or could we add a note in the readme?

Exactly. [History.md](https://github.com/ruby/rdoc/blob/master/History.rdoc) is best place that.

**Comment by cooperka** [comment]
I'm sorry, I didn't mean to make work for you during a holiday. This has been around for months and is not urgent.

I'll submit a PR later during the work week to History.md (it hasn't been updated since 2017, so I'm glad to know you'd still accept a PR for it). Part of my role as an open source developer is to help you document; we can all help each other. I like to cooperate, not boss you around.

**Comment by alexjfisher** [comment]
I don't understand why semver hasn't been followed.  From the history.md it looks like it was in the past.

From https://guides.rubygems.org/patterns/#semantic-versioning

> The RubyGems team urges gem developers to follow the Semantic Versioning standard for their gem’s versions. The RubyGems library itself does not enforce a strict versioning policy, but using an “irrational” policy will only be a disservice to those in the community who use your gems.

**Comment by deivid-rodriguez** [comment]
Just posting the same tip here as in ruby/psych#531. If it's the same issue, an alternative solution to pinning Psych or RDoc would be to upgrade RubyGems with `gem update --system`.

**Comment by hsbt** [comment]
I investigate this again. Depending on Psych 4+ is intentional changes. https://github.com/ruby/rdoc/commit/f0141d4e95da66710343920252f22f751d83b9ce

It's better to put this change into a changelog or other document. We always welcome your contribute. Thanks.
