### ISSUE TITLE
Changelog / release notes

### ISSUE THREAD

**Issue by slondr** [ruby/rdoc#920]
I'm in the process of updating the dependencies of an old project of mine, and I've reached rdoc. Unfortunately I can't seem to find any documentation for what changes are associated with version number bumps. There is a "history" file, but that hasn't been updated since 2017. 

I'm especially confused by the versioning semantics for rdoc. It seems like there are "patch" releases for 6.1 going out after 6.3 released; is 6.1 -> 6.3 a breaking change? If so, what broke?

**Comment by hsbt** [comment]
I filed changes with `gh release create`. see https://github.com/ruby/rdoc/releases.

I will create them when releasing the new version in the future. Thanks!
