### ISSUE TITLE
Linkable Images

### ISSUE THREAD

**Issue by TwP** [ruby/rdoc#93]
`{http://example.com/foo.png}[http://example.com]` should generate a linkable image `<a href="http://example.com><img src="http://example.com/foo.png></a>`

Currently the only way to do this is to explicitly put an image tag in the label `{<img src="foo.png">}[http://example.com]`

**Comment by franklinyu** [comment]
@drbrain How does your example work? Did you mean that the image URL is `http://example/image`? That doesn't looks like a URL. If "fully qualified name" means that the domain name should be like `www.example.com` instead of `example.com`, then I found that

```rdoc
{rdoc-image:https://avatars0.githubusercontent.com/u/9831?v=3&s=460}[https://www.google.com]
```

didn't work.

**Comment by jzuniga77** [comment]
Is it possible to use local assets here instead of links?
