### ISSUE TITLE
Possible ReDos in the read_directive method

### ISSUE THREAD

**Issue by Akashkarmakar787** [ruby/rdoc#995]
There is a possible ReDos issue
https://github.com/ruby/rdoc/blob/master/lib/rdoc/parser/ruby.rb#L2137 with string for example: `'0'*54773 + '\x000:'`

https://github.com/ruby/rdoc/blob/master/lib/rdoc/comment.rb#L100 with string ex: `'\n'*106500100 + 'call-seq:' + 'a'*165100000`

**Comment by Akashkarmakar787** [comment]
@nobu do we need to have a CVE for this?

**Comment by nobu** [comment]
No, we do not believe it is necessary.
Do you know services providing arbitrary documents, using RDoc and Ruby 3.1 or earlier?

**Comment by Akashkarmakar787** [comment]
> No, we do not believe it is necessary. Do you know services providing arbitrary documents, using RDoc and Ruby 3.1 or earlier?

I am not sure @nobu if some service provides that. But i believe it will be better if we have a CVE as user will make informed decision.
